---
title: "Storms"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: fill
    
---

```{r setup, include = FALSE}
# DO NOT ALTER CODE IN THIS CHUNK
# Set knitr options
knitr::opts_chunk$set(
  echo = TRUE, eval = TRUE, fig.width = 5,
  fig.asp = 0.618, out.width = "80%", dpi = 120,
  fig.align = "center", cache = FALSE
)

# Load packages
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(highcharter))
suppressPackageStartupMessages(library(leaflet))
suppressPackageStartupMessages(library(plotly))
suppressPackageStartupMessages(library(lubridate))

```


```{r, include = FALSE}
storms = storms[,c(-12,-13)]
date = make_date(year = storms$year, month = storms$month, day = storms$day)

storms = cbind(storms, date)
```

Understanding the Data
===========================

Column {data-width=600}
-------------------------------------

###Line Plot: Wind vs. Pressure

```{r, echo = FALSE, eval = TRUE}

lineplot = ggplot(data = storms, mapping = aes(x = wind, y = pressure, color = status)) + geom_line()
ggplotly(lineplot)

```

Column {data-width=400}
-------------------------------------
### Bar Graph: How Category Relates to Status 

```{r, echo = FALSE, eval = TRUE}
barplot = ggplot(data = storms, mapping = aes(x=status, fill=category)) + geom_bar()
ggplotly(barplot)
```

### Bar Graph: Number of Hurricanes for Each Decade

```{r, echo = FALSE, eval = TRUE}
histogram = ggplot(data = storms, mapping = aes(x=year, fill = category), ) + geom_histogram(binwidth = 10, position = "dodge2") 
ggplotly(histogram)
``` 


1975-1985
================================


### Map by Names
```{r, echo = FALSE, eval = TRUE}
#1975-1985 for Names

stormsnames1 = storms %>% slice(1:1554)
stormsnames1 = stormsnames1[order(stormsnames1$name),]

stormsnamescolor1 = colorFactor ( palette = c("purple", "blue","cyan", "green", "yellow", "orange",  "red"), domain = stormsnames1$category)

leaflet() %>% 
  addProviderTiles(providers$ CartoDB.DarkMatter) %>%
  
  addCircleMarkers(
    lat = stormsnames1$lat, 
    lng = stormsnames1$long,  
    popup = paste(
      "Name:", stormsnames1$name,
      "<br>", "Category:", stormsnames1$category, 
      "<br>","Status:", stormsnames1$status, 
      "<br>", "Date:", stormsnames1$date, 
      "<br>", "Hour:", stormsnames1$hour), 
    color = stormsnamescolor1(stormsnames1$category), 
    group = stormsnames1$name) %>%
  
  addLayersControl(
    baseGroups = stormsnames1$name,
    options = layersControlOptions(collapsed=FALSE)) %>%
  
  addLegend(
    'bottomleft', 
    pal = stormsnamescolor1, 
    values = stormsnames1$category,
    title = 'Category',
    opacity = 1)

```

### Map by Category

```{r, echo = FALSE, eval = TRUE}
#1975-1985 for Category

stormscategory1 = storms %>% slice(1:1554)
stormscategory1 = stormscategory1[order(stormscategory1$category),]

stormscategorycolor1 = colorFactor ( palette = c("purple", "blue","cyan", "green", "yellow", "orange",  "red"), domain = stormscategory1$category)

leaflet() %>% 
  addProviderTiles(providers$ CartoDB.DarkMatter) %>%
  
  addCircleMarkers(
    lat = stormscategory1$lat, 
    lng = stormscategory1$long,  
    popup = paste(
      "Name:", stormscategory1$name,
      "<br>", "Category:", stormscategory1$category, 
      "<br>","Status:", stormscategory1$status, 
      "<br>", "Date:", stormscategory1$date, 
      "<br>", "Hour:", stormscategory1$hour), 
    color = stormscategorycolor1(stormscategory1$category), 
    group = stormscategory1$category) %>%
  
  addLayersControl(
    overlayGroups = stormscategory1$category,
    options = layersControlOptions(collapsed=FALSE)) %>%
  
  hideGroup(c("0", "1", "2", "3", "4", "-1")) %>%
  
  addLegend(
    'bottomleft', 
    pal = stormscategorycolor1, 
    values = stormscategory1$category,
    title = 'Category',
    opacity = 1)


```

1986-1995
===========================

### Map by Names

```{r, echo = FALSE, eval = TRUE}
#1985-1995 for Names

stormsnames2 = storms %>% slice(1555:3984)
stormsnames2 = stormsnames2[order(stormsnames2$name),]

stormsnamescolor2 = colorFactor ( palette = c("purple", "blue","cyan", "green", "yellow", "orange",  "red"), domain = stormsnames2$category)

leaflet() %>% 
  addProviderTiles(providers$ CartoDB.DarkMatter) %>%
  
  addCircleMarkers(
    lat = stormsnames2$lat, 
    lng = stormsnames2$long,  
    popup = paste(
      "Name:", stormsnames2$name,
      "<br>", "Category:", stormsnames2$category, 
      "<br>","Status:", stormsnames2$status, 
      "<br>", "Date:", stormsnames2$date, 
      "<br>", "Hour:", stormsnames2$hour), 
    color = stormsnamescolor2(stormsnames2$category), 
    group = stormsnames2$name) %>%
  
  addLayersControl(
    baseGroups = stormsnames2$name,
    options = layersControlOptions(collapsed=FALSE)) %>%
  
  addLegend(
    'bottomleft', 
    pal = stormsnamescolor2, 
    values = stormsnames2$category,
    title = 'Category',
    opacity = 1)

```

### Map by Category

```{r, echo = FALSE, eval = TRUE}
#1985-1995 for Category

stormscategory2 = storms %>% slice(1555:3984)
stormscategory2 = stormscategory2[order(stormscategory2$category),]

stormscategorycolor2 = colorFactor ( palette = c("purple", "blue","cyan", "green", "yellow", "orange",  "red"), domain = stormscategory2$category)

leaflet() %>% 
  addProviderTiles(providers$ CartoDB.DarkMatter) %>%
  
  addCircleMarkers(
    lat = stormscategory2$lat, 
    lng = stormscategory2$long,  
    popup = paste(
      "Name:", stormscategory2$name,
      "<br>", "Category:", stormscategory2$category, 
      "<br>","Status:", stormscategory2$status, 
      "<br>", "Date:", stormscategory2$date, 
      "<br>", "Hour:", stormscategory2$hour), 
    color = stormscategorycolor2(stormscategory2$category), 
    group = stormscategory2$category) %>%
  
  addLayersControl(
    overlayGroups = stormscategory2$category,
    options = layersControlOptions(collapsed=FALSE)) %>%
  
  hideGroup(c("0", "1", "2", "3", "4", "-1")) %>%
  
  addLegend(
    'bottomleft', 
    pal = stormscategorycolor2, 
    values = stormscategory2$category,
    title = 'Category',
    opacity = 1)


```

1996-2005
===========================

### Map by Names

```{r, echo = FALSE, eval = TRUE}
#1995-2005 for Names

stormsnames3 = storms %>% slice(3985:7379)
stormsnames3 = stormsnames3[order(stormsnames3$name),]

stormsnamescolor3 = colorFactor ( palette = c("purple", "blue","cyan", "green", "yellow", "orange",  "red"), domain = stormsnames3$category)

leaflet() %>% 
  addProviderTiles(providers$ CartoDB.DarkMatter) %>%
  
  addCircleMarkers(
    lat = stormsnames3$lat, 
    lng = stormsnames3$long,  
    popup = paste(
      "Name:", stormsnames3$name,
      "<br>", "Category:", stormsnames3$category, 
      "<br>","Status:", stormsnames3$status, 
      "<br>", "Date:", stormsnames3$date, 
      "<br>", "Hour:", stormsnames3$hour), 
    color = stormsnamescolor3(stormsnames3$category), 
    group = stormsnames3$name) %>%
  
  addLayersControl(
    baseGroups = stormsnames3$name,
    options = layersControlOptions(collapsed=FALSE)) %>%
  
  addLegend(
    'bottomleft', 
    pal = stormsnamescolor3, 
    values = stormsnames3$category,
    title = 'Category',
    opacity = 1)

```


### Map by Category

```{r, echo = FALSE, eval = TRUE}
#1995-2005 for Category

stormscategory3 = storms %>% slice(3985:7379)
stormscategory3 = stormscategory3[order(stormscategory3$category),]

stormscategorycolor3 = colorFactor ( palette = c("purple", "blue","cyan", "green", "yellow", "orange",  "red"), domain = stormscategory3$category)

leaflet() %>% 
  addProviderTiles(providers$ CartoDB.DarkMatter) %>%
  
  addCircleMarkers(
    lat = stormscategory3$lat, 
    lng = stormscategory3$long,  
    popup = paste(
      "Name:", stormscategory3$name,
      "<br>", "Category:", stormscategory3$category, 
      "<br>","Status:", stormscategory3$status, 
      "<br>", "Date:", stormscategory3$date, 
      "<br>", "Hour:", stormscategory3$hour), 
    color = stormscategorycolor3(stormscategory3$category), 
    group = stormscategory3$category) %>%
  
  addLayersControl(
    overlayGroups = stormscategory3$category,
    options = layersControlOptions(collapsed=FALSE)) %>%
  
  hideGroup(c("0", "1", "2", "3", "4", "-1")) %>%
  
  addLegend(
    'bottomleft', 
    pal = stormscategorycolor3, 
    values = stormscategory3$category,
    title = 'Category',
    opacity = 1)


```

2006-2015
===========================

### Map by Names

```{r, echo = FALSE, eval = TRUE}
#2005-2015 for Names

stormsnames4 = storms %>% slice(7380:10010)
stormsnames4 = stormsnames4[order(stormsnames4$name),]

stormsnamescolor4 = colorFactor ( palette = c("purple", "blue","cyan", "green", "yellow", "orange",  "red"), domain = stormsnames4$category)

leaflet() %>% 
  addProviderTiles(providers$ CartoDB.DarkMatter) %>%
  
  addCircleMarkers(
    lat = stormsnames4$lat, 
    lng = stormsnames4$long,  
    popup = paste(
      "Name:", stormsnames4$name,
      "<br>", "Category:", stormsnames4$category, 
      "<br>","Status:", stormsnames4$status, 
      "<br>", "Date:", stormsnames4$date, 
      "<br>", "Hour:", stormsnames4$hour), 
    color = stormsnamescolor4(stormsnames4$category), 
    group = stormsnames4$name) %>%
  
  addLayersControl(
    baseGroups = stormsnames4$name,
    options = layersControlOptions(collapsed=FALSE)) %>%
  
  addLegend(
    'bottomleft', 
    pal = stormsnamescolor4, 
    values = stormsnames4$category,
    title = 'Category',
    opacity = 1)

```

### Map by Category

```{r, echo = FALSE, eval = TRUE}
#2005-2015 for Category

stormscategory4 = storms %>% slice(7380:10010)
stormscategory4 = stormscategory4[order(stormscategory4$category),]

stormscategorycolor4 = colorFactor ( palette = c("purple", "blue","cyan", "green", "yellow", "orange",  "red"), domain = stormscategory4$category)

leaflet() %>% 
  addProviderTiles(providers$ CartoDB.DarkMatter) %>%
  
  addCircleMarkers(
    lat = stormscategory4$lat, 
    lng = stormscategory4$long,  
    popup = paste(
      "Name:", stormscategory4$name,
      "<br>", "Category:", stormscategory4$category, 
      "<br>","Status:", stormscategory4$status, 
      "<br>", "Date:", stormscategory4$date, 
      "<br>", "Hour:", stormscategory4$hour), 
    color = stormscategorycolor4(stormscategory4$category), 
    group = stormscategory4$category) %>%
  
  addLayersControl(
    overlayGroups = stormscategory4$category,
    options = layersControlOptions(collapsed=FALSE)) %>%
  
  hideGroup(c("0", "1", "2", "3", "4", "-1")) %>%
  
  addLegend(
    'bottomleft', 
    pal = stormscategorycolor4, 
    values = stormscategory4$category,
    title = 'Category',
    opacity = 1)


```